In [1]:
print("hello world")

hello world


In [2]:
a=19

In [3]:
a

19

In [5]:
import numpy as np



In [6]:
ls=[1,2,3,4,5]
arr=np.array(ls)
arr

array([1, 2, 3, 4, 5])

In [7]:
ls

[1, 2, 3, 4, 5]

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
ls*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [10]:
arr*2

array([ 2,  4,  6,  8, 10])

In [11]:
arr**2

array([ 1,  4,  9, 16, 25])

In [12]:
sq_ls=[1]
for i in ls:
    sq_ls.append(i**2)
sq_ls

[1, 1, 4, 9, 16, 25]

In [14]:
[x**2 for x in ls]   #list comprehension

[1, 4, 9, 16, 25]

In [16]:
arr1=np.array((5,3,7,2,1))
arr1

array([5, 3, 7, 2, 1])

In [17]:
arr2=np.array(['heema','rekha','jaya'])
arr2


array(['heema', 'rekha', 'jaya'], dtype='<U5')

In [19]:
arr3=np.arange(1,1001,10)
arr3

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121,
       131, 141, 151, 161, 171, 181, 191, 201, 211, 221, 231, 241, 251,
       261, 271, 281, 291, 301, 311, 321, 331, 341, 351, 361, 371, 381,
       391, 401, 411, 421, 431, 441, 451, 461, 471, 481, 491, 501, 511,
       521, 531, 541, 551, 561, 571, 581, 591, 601, 611, 621, 631, 641,
       651, 661, 671, 681, 691, 701, 711, 721, 731, 741, 751, 761, 771,
       781, 791, 801, 811, 821, 831, 841, 851, 861, 871, 881, 891, 901,
       911, 921, 931, 941, 951, 961, 971, 981, 991])